server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v0/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/default
            - id: b-service
              uri: http://localhost:8082
              predicates:
                - Path=/b-service/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bServiceCircuitBreaker
                    fallbackUri: forward:/fallback/default
          discovery:
            locator:
              enabled: true
